### PR TITLE
Add Cards Component

### PR DESCRIPTION
**Pull request by Avuidrauxs**
### Description
- Added Cards from recipe-antd

### CODE REVIEW

**Comment by Avuidrauxs** [comment]
@atherdon , Am i on the right track

**Comment by atherdon** [comment]
@Avuidrauxs looks awesome! Did you finish, so i can merge things?

**Comment by Avuidrauxs** [comment]
@atherdon , is it good enough to bemerged or are there other stuff I need first?

**Comment by atherdon** [comment]
it's looks as it should look :) i just mean - did you move all components that you needed? i just don't remember

**Comment by Avuidrauxs** [comment]
@atherdon , Yes I moved all the cards as listed in the `README.md`

**Comment by atherdon** [comment]
ok, then i'm merging the changes! thanks!

**Pull request merged**
